# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Soil Erodability K Script.py
# Created on: 2018-10-24 22:15:59.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: Soil Erodability K Script <Organic_Percent_Raster> <Silt_Percent_Raster> <Sand_Percent_Raster> <Interim_file> <Soil_erodibility__K_> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
Organic_Percent_Raster = arcpy.GetParameterAsText(0)
if Organic_Percent_Raster == '#' or not Organic_Percent_Raster:
    Organic_Percent_Raster = "H:\\GIS\\" # provide a default value if unspecified

Silt_Percent_Raster = arcpy.GetParameterAsText(1)
if Silt_Percent_Raster == '#' or not Silt_Percent_Raster:
    Silt_Percent_Raster = "H:\\GIS\\" # provide a default value if unspecified

Sand_Percent_Raster = arcpy.GetParameterAsText(2)
if Sand_Percent_Raster == '#' or not Sand_Percent_Raster:
    Sand_Percent_Raster = "H:\\GIS\\" # provide a default value if unspecified

Interim_file = arcpy.GetParameterAsText(3)
if Interim_file == '#' or not Interim_file:
    Interim_file = "H:\\GIS\\v" # provide a default value if unspecified

Soil_erodibility__K_ = arcpy.GetParameterAsText(4)
if Soil_erodibility__K_ == '#' or not Soil_erodibility__K_:
    Soil_erodibility__K_ = "H:\\GIS\\k_factor" # provide a default value if unspecified

# Local variables:

# Process: Raster Calculator
arcpy.gp.RasterCalculator_sa("Con((\"%Silt Percent Raster%\" > 0) & (\"%Silt Percent Raster%\"  <= 10), \"%Silt Percent Raster%\" * 0.0 + \"%Sand Percent Raster%\" * 0.0 + \"%Organic Percent Raster%\" * 0.01, Con((\"%Silt Percent Raster%\" > 10) & (\"%Silt Percent Raster%\"  <= 20),\"%Silt Percent Raster%\" * 0.001166 + \"%Sand Percent Raster%\" * 0.00178 + \"%Organic Percent Raster%\" * -0.03, Con((\"%Silt Percent Raster%\" > 20) & (\"%Silt Percent Raster%\" <= 30), \"%Silt Percent Raster%\" * 0.00265 + \"%Sand Percent Raster%\" * 0.00124 + \"%Organic Percent Raster%\" * -0.0109, Con((\"%Silt Percent Raster%\" > 30) & (\"%Silt Percent Raster%\" <= 40), \"%Silt Percent Raster%\" * 0.00348 + \"%Sand Percent Raster%\" * 0.00173 + \"%Organic Percent Raster%\" * -0.0162, Con((\"%Silt Percent Raster%\" > 40) & (\"%Silt Percent Raster%\" <= 50), \"%Silt Percent Raster%\" * 0.00430 + \"%Sand Percent Raster%\" * 0.00169 + \"%Organic Percent Raster%\" * -0.01891, Con((\"%Silt Percent Raster%\" > 50) & (\"%Silt Percent Raster%\" <= 60), \"%Silt Percent Raster%\" * 0.00443 + \"%Sand Percent Raster%\" * 0.00123 + \"%Organic Percent Raster%\" * -0.01140, Con((\"%Silt Percent Raster%\" > 60) & (\"%Silt Percent Raster%\" <= 70), \"%Silt Percent Raster%\" * 0.00587 + \"%Sand Percent Raster%\" * 0.00352 + \"%Organic Percent Raster%\" * -0.03523, Con((\"%Silt Percent Raster%\" > 70) &  (\"%Silt Percent Raster%\" <= 80), \"%Silt Percent Raster%\" * 0.00555 + \"%Sand Percent Raster%\" * 0.00122 + \"%Organic Percent Raster%\" * -0.00888, Con((\"%Silt Percent Raster%\" > 80) & (\"%Silt Percent Raster%\" <= 90), \"%Silt Percent Raster%\" * 0.006 + \"%Sand Percent Raster%\" * 0.008 + \"%Organic Percent Raster%\" * -0.048, \"%Silt Percent Raster%\" * 0.00848+ \"%Sand Percent Raster%\" * -0.01651 + \"%Organic Percent Raster%\" * -0.10651)))))))))", Interim_file)

# Process: Raster Calculator (2)
arcpy.gp.RasterCalculator_sa("Con(\"%Interim file%\" <= 0,0,\"%Interim file%\")", Soil_erodibility__K_)

