# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# BandStatsInterface.py
# Author : Sherbaz Hashmi
# Created on: 2018-08-17 14:15:44.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: Facade to interface with BandStats Class to Retrieve Band Statstics.
# ---------------------------------------------------------------------------
import arcpy
from arcpy import env
from arcpy.sa import *

class BandStatsInterface():

    def __init__(self, location, isDetailed):
       #print("Running Init Function + "+outputLocation)
        self.isDetailed = isDetailed
        self.outputLocation = location


    def setupWorkspace(self):
        # Setting Up Environment
        env.workspace = "C:/Users/Sherbaz/Desktop/GIS/L8_composite.tif"

    def selectBands(self):
        # Storing Bands to Use
        self.bands = ["Band_1","Band_2","Band_3","Band_4","Band_5", "Band_6","Band_7"]
        print("Selected Bands")

    def setupEnvironment(self):
        self.setupWorkspace()
        self.selectBands()

    def generateBandCollectionStats(self):
        print("Output Location : "+ self.outputLocation)
        self.setupEnvironment();
        if(self.isDetailed):
            BandCollectionStats(self.bands,self.outputLocation+"bc_stats_detailed.txt","DETAILED")
        else:
            BandCollectionStats(self.bands,self.outputLocation+"bc_stats_brief.txt","BRIEF")

bandStats = BandStatsInterface("C:/Users/Sherbaz/Desktop/GIS/", True)
bandStats.generateBandCollectionStats();

