# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# test_script.py
# Created on: 2018-08-31 13:36:47.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
dem_tif = "C:\\Users\\Sherbaz\\Desktop\\GIS\\dem.tif"
Minus_dem2 = "C:\\Users\\Sherbaz\\Desktop\\GIS\\Minus_dem2"

# Process: Minus
arcpy.gp.Minus_sa(dem_tif, "", Minus_dem2)

